### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [lbartk/MMM-SwissAlpLakes#1]
It would be nice if you would put the screenshots into the repository. Then one of them will be shown in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/).

**Comment by lbartk** [comment]
@KristjanESPERANTO Thank you for your message. The file "screenshot.png" has been uploaded on top of printscreens in the description.

**Comment by KristjanESPERANTO** [comment]
Nice. Now the screenshot is displayed in the new module list :rocket: Thanks for the quick reaction! :slightly_smiling_face:
